apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iperf-client-monitor
  namespace: raf
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      name: iperf-client
      component: metrics
  endpoints:
    - port: iperf-metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - raf
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-client-monitor
  namespace: raf
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      name: ping-client
      component: metrics
  endpoints:
    - port: ping-metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - raf
