apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: raf 
data:
  additional-scrape-configs.yaml: |
    - job_name: 'iperf-client'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - raf 
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: iperf-client
      metrics_path: /metrics
    - job_name: 'ping-client'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - raf 
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: ping-client
      metrics_path: /metrics
