apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
  namespace: raf 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      containers:
      - name: iperf-server
        image: ptrvx/iperf-server:latest
        ports:
        - containerPort: 5201
        resources:
          limits:
            memory: 512Mi
            cpu: "500m"
          requests:
            memory: 256Mi
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-server
  namespace: raf 
spec:
  selector:
    app: iperf-server
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
  type: ClusterIP
